# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabbed.ui'
#
# Created: Wed Oct 21 16:42:33 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LWCAttendanceTaker(object):
    def setupUi(self, LWCAttendanceTaker):
        LWCAttendanceTaker.setObjectName(_fromUtf8("LWCAttendanceTaker"))
        LWCAttendanceTaker.resize(1050, 644)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LWCAttendanceTaker.sizePolicy().hasHeightForWidth())
        LWCAttendanceTaker.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(LWCAttendanceTaker)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_quit = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setObjectName(_fromUtf8("pushButton_quit"))
        self.horizontalLayout.addWidget(self.pushButton_quit)
        self.gridLayout_5.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.tab_widget = QtGui.QTabWidget(self.centralwidget)
        self.tab_widget.setObjectName(_fromUtf8("tab_widget"))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_6)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 393, 351))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.comboBox_serialPort = QtGui.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_serialPort.setFont(font)
        self.comboBox_serialPort.setObjectName(_fromUtf8("comboBox_serialPort"))
        self.verticalLayout.addWidget(self.comboBox_serialPort)
        self.pushButton_refresh = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_refresh.setFont(font)
        self.pushButton_refresh.setObjectName(_fromUtf8("pushButton_refresh"))
        self.verticalLayout.addWidget(self.pushButton_refresh)
        self.pushButton_connect = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_connect.setFont(font)
        self.pushButton_connect.setObjectName(_fromUtf8("pushButton_connect"))
        self.verticalLayout.addWidget(self.pushButton_connect)
        self.pushButton_disconnect = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_disconnect.setFont(font)
        self.pushButton_disconnect.setObjectName(_fromUtf8("pushButton_disconnect"))
        self.verticalLayout.addWidget(self.pushButton_disconnect)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_5 = QtGui.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_19 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.pushButton_dbconnect = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_dbconnect.setObjectName(_fromUtf8("pushButton_dbconnect"))
        self.gridLayout_19.addWidget(self.pushButton_dbconnect, 1, 0, 1, 1)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.databaseHostLabel = QtGui.QLabel(self.groupBox_5)
        self.databaseHostLabel.setObjectName(_fromUtf8("databaseHostLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.databaseHostLabel)
        self.databaseHostLineEdit = QtGui.QLineEdit(self.groupBox_5)
        self.databaseHostLineEdit.setObjectName(_fromUtf8("databaseHostLineEdit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.databaseHostLineEdit)
        self.gridLayout_19.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.pushButton_connecttohome = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_connecttohome.setObjectName(_fromUtf8("pushButton_connecttohome"))
        self.gridLayout_19.addWidget(self.pushButton_connecttohome, 2, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.tab_widget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_attendance = QtGui.QWidget()
        self.tab_attendance.setObjectName(_fromUtf8("tab_attendance"))
        self.label_4 = QtGui.QLabel(self.tab_attendance)
        self.label_4.setGeometry(QtCore.QRect(9, 9, 442, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab_attendance)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 60, 401, 421))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_4 = QtGui.QGroupBox(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget.setGeometry(QtCore.QRect(7, 30, 311, 171))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout_2 = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_static_time = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_static_time.setFont(font)
        self.label_static_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_static_time.setObjectName(_fromUtf8("label_static_time"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_static_time)
        self.lcdNumber_time = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_time.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lcdNumber_time.setFont(font)
        self.lcdNumber_time.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 127);\n"
"}"))
        self.lcdNumber_time.setObjectName(_fromUtf8("lcdNumber_time"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lcdNumber_time)
        self.label_static_date = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_static_date.setFont(font)
        self.label_static_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_static_date.setObjectName(_fromUtf8("label_static_date"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_static_date)
        self.label_dynamic_date = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_dynamic_date.setFont(font)
        self.label_dynamic_date.setText(_fromUtf8(""))
        self.label_dynamic_date.setObjectName(_fromUtf8("label_dynamic_date"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_dynamic_date)
        self.label_static_event = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_static_event.setFont(font)
        self.label_static_event.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_static_event.setObjectName(_fromUtf8("label_static_event"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_static_event)
        self.label_dynamic_event = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_dynamic_event.sizePolicy().hasHeightForWidth())
        self.label_dynamic_event.setSizePolicy(sizePolicy)
        self.label_dynamic_event.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_dynamic_event.setFont(font)
        self.label_dynamic_event.setStyleSheet(_fromUtf8("qproperty-alignment: \'AlignVCenter | AlignLeft\';"))
        self.label_dynamic_event.setText(_fromUtf8(""))
        self.label_dynamic_event.setWordWrap(True)
        self.label_dynamic_event.setObjectName(_fromUtf8("label_dynamic_event"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_dynamic_event)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_2 = QtGui.QGroupBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_static_name = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_static_name.setFont(font)
        self.label_static_name.setObjectName(_fromUtf8("label_static_name"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_static_name)
        self.label_dynamic_name = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_dynamic_name.setFont(font)
        self.label_dynamic_name.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_dynamic_name.setText(_fromUtf8(""))
        self.label_dynamic_name.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_dynamic_name.setObjectName(_fromUtf8("label_dynamic_name"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_dynamic_name)
        self.label_static_dummy = QtGui.QLabel(self.groupBox_2)
        self.label_static_dummy.setText(_fromUtf8(""))
        self.label_static_dummy.setObjectName(_fromUtf8("label_static_dummy"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_static_dummy)
        self.label_dynamic_engname = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_dynamic_engname.setFont(font)
        self.label_dynamic_engname.setText(_fromUtf8(""))
        self.label_dynamic_engname.setWordWrap(True)
        self.label_dynamic_engname.setObjectName(_fromUtf8("label_dynamic_engname"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_dynamic_engname)
        self.label_static_rfid = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_static_rfid.setFont(font)
        self.label_static_rfid.setObjectName(_fromUtf8("label_static_rfid"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_static_rfid)
        self.label_dynamic_rfid = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_dynamic_rfid.setFont(font)
        self.label_dynamic_rfid.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_dynamic_rfid.setText(_fromUtf8(""))
        self.label_dynamic_rfid.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_dynamic_rfid.setObjectName(_fromUtf8("label_dynamic_rfid"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_dynamic_rfid)
        self.label_static_dept = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_static_dept.setFont(font)
        self.label_static_dept.setObjectName(_fromUtf8("label_static_dept"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_static_dept)
        self.label_dynamic_dept = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_dynamic_dept.setFont(font)
        self.label_dynamic_dept.setText(_fromUtf8(""))
        self.label_dynamic_dept.setObjectName(_fromUtf8("label_dynamic_dept"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.label_dynamic_dept)
        self.label_static_status = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_static_status.setFont(font)
        self.label_static_status.setObjectName(_fromUtf8("label_static_status"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_static_status)
        self.label_dynamic_status = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_dynamic_status.setFont(font)
        self.label_dynamic_status.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_dynamic_status.setText(_fromUtf8(""))
        self.label_dynamic_status.setScaledContents(False)
        self.label_dynamic_status.setWordWrap(True)
        self.label_dynamic_status.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_dynamic_status.setObjectName(_fromUtf8("label_dynamic_status"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.label_dynamic_status)
        self.gridLayout_20.addLayout(self.formLayout, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.label_picture = QtGui.QLabel(self.tab_attendance)
        self.label_picture.setGeometry(QtCore.QRect(450, 280, 211, 191))
        self.label_picture.setMinimumSize(QtCore.QSize(160, 160))
        self.label_picture.setText(_fromUtf8(""))
        self.label_picture.setPixmap(QtGui.QPixmap(_fromUtf8("../unknown_profile.png")))
        self.label_picture.setObjectName(_fromUtf8("label_picture"))
        self.tab_widget.addTab(self.tab_attendance, _fromUtf8(""))
        self.tab_statistics = QtGui.QWidget()
        self.tab_statistics.setObjectName(_fromUtf8("tab_statistics"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_statistics)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tabWidget_statistics = QtGui.QTabWidget(self.tab_statistics)
        self.tabWidget_statistics.setObjectName(_fromUtf8("tabWidget_statistics"))
        self.tab_sundayservice = QtGui.QWidget()
        self.tab_sundayservice.setObjectName(_fromUtf8("tab_sundayservice"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tab_sundayservice)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.stackedWidget_ss = QtGui.QStackedWidget(self.tab_sundayservice)
        self.stackedWidget_ss.setObjectName(_fromUtf8("stackedWidget_ss"))
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.gridLayout_31 = QtGui.QGridLayout(self.page_6)
        self.gridLayout_31.setObjectName(_fromUtf8("gridLayout_31"))
        self.mpl_sundayservicestats = MplWidget(self.page_6)
        self.mpl_sundayservicestats.setObjectName(_fromUtf8("mpl_sundayservicestats"))
        self.gridLayout_31.addWidget(self.mpl_sundayservicestats, 0, 0, 1, 1)
        self.stackedWidget_ss.addWidget(self.page_6)
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.gridLayout_24 = QtGui.QGridLayout(self.page_7)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.mpl_sundayservice_daily = MplWidget(self.page_7)
        self.mpl_sundayservice_daily.setObjectName(_fromUtf8("mpl_sundayservice_daily"))
        self.gridLayout_24.addWidget(self.mpl_sundayservice_daily, 0, 0, 1, 1)
        self.stackedWidget_ss.addWidget(self.page_7)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_10 = QtGui.QGridLayout(self.page)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.mpl_sundayservicedeptstats = MplWidget(self.page)
        self.mpl_sundayservicedeptstats.setObjectName(_fromUtf8("mpl_sundayservicedeptstats"))
        self.gridLayout_10.addWidget(self.mpl_sundayservicedeptstats, 0, 0, 1, 1)
        self.stackedWidget_ss.addWidget(self.page)
        self.horizontalLayout_3.addWidget(self.stackedWidget_ss)
        self.gridLayout_12.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.pushButton_previous_graph_ss = QtGui.QPushButton(self.tab_sundayservice)
        self.pushButton_previous_graph_ss.setObjectName(_fromUtf8("pushButton_previous_graph_ss"))
        self.horizontalLayout_12.addWidget(self.pushButton_previous_graph_ss)
        self.pushButton_next_graph_ss = QtGui.QPushButton(self.tab_sundayservice)
        self.pushButton_next_graph_ss.setObjectName(_fromUtf8("pushButton_next_graph_ss"))
        self.horizontalLayout_12.addWidget(self.pushButton_next_graph_ss)
        self.gridLayout_12.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        self.tabWidget_statistics.addTab(self.tab_sundayservice, _fromUtf8(""))
        self.tab_wednesdayservice = QtGui.QWidget()
        self.tab_wednesdayservice.setObjectName(_fromUtf8("tab_wednesdayservice"))
        self.gridLayout_14 = QtGui.QGridLayout(self.tab_wednesdayservice)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.stackedWidget_ws = QtGui.QStackedWidget(self.tab_wednesdayservice)
        self.stackedWidget_ws.setObjectName(_fromUtf8("stackedWidget_ws"))
        self.page_8 = QtGui.QWidget()
        self.page_8.setObjectName(_fromUtf8("page_8"))
        self.gridLayout_29 = QtGui.QGridLayout(self.page_8)
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.mpl_weddayservicestats = MplWidget(self.page_8)
        self.mpl_weddayservicestats.setObjectName(_fromUtf8("mpl_weddayservicestats"))
        self.gridLayout_29.addWidget(self.mpl_weddayservicestats, 0, 0, 1, 1)
        self.stackedWidget_ws.addWidget(self.page_8)
        self.page_9 = QtGui.QWidget()
        self.page_9.setObjectName(_fromUtf8("page_9"))
        self.gridLayout_25 = QtGui.QGridLayout(self.page_9)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.mpl_wednesdayservice_daily = MplWidget(self.page_9)
        self.mpl_wednesdayservice_daily.setObjectName(_fromUtf8("mpl_wednesdayservice_daily"))
        self.gridLayout_25.addWidget(self.mpl_wednesdayservice_daily, 0, 0, 1, 1)
        self.stackedWidget_ws.addWidget(self.page_9)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_21 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.mpl_weddayservicedeptstats = MplWidget(self.page_2)
        self.mpl_weddayservicedeptstats.setObjectName(_fromUtf8("mpl_weddayservicedeptstats"))
        self.gridLayout_21.addWidget(self.mpl_weddayservicedeptstats, 0, 0, 1, 1)
        self.stackedWidget_ws.addWidget(self.page_2)
        self.horizontalLayout_4.addWidget(self.stackedWidget_ws)
        self.gridLayout_14.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.pushButton_previous_graph_ws = QtGui.QPushButton(self.tab_wednesdayservice)
        self.pushButton_previous_graph_ws.setObjectName(_fromUtf8("pushButton_previous_graph_ws"))
        self.horizontalLayout_13.addWidget(self.pushButton_previous_graph_ws)
        self.pushButton_next_graph_ws = QtGui.QPushButton(self.tab_wednesdayservice)
        self.pushButton_next_graph_ws.setObjectName(_fromUtf8("pushButton_next_graph_ws"))
        self.horizontalLayout_13.addWidget(self.pushButton_next_graph_ws)
        self.gridLayout_14.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.tabWidget_statistics.addTab(self.tab_wednesdayservice, _fromUtf8(""))
        self.tab_fridayprayer = QtGui.QWidget()
        self.tab_fridayprayer.setObjectName(_fromUtf8("tab_fridayprayer"))
        self.gridLayout_16 = QtGui.QGridLayout(self.tab_fridayprayer)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.stackedWidget_fpm = QtGui.QStackedWidget(self.tab_fridayprayer)
        self.stackedWidget_fpm.setObjectName(_fromUtf8("stackedWidget_fpm"))
        self.page_10 = QtGui.QWidget()
        self.page_10.setObjectName(_fromUtf8("page_10"))
        self.gridLayout_30 = QtGui.QGridLayout(self.page_10)
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.mpl_fridayservicestats = MplWidget(self.page_10)
        self.mpl_fridayservicestats.setObjectName(_fromUtf8("mpl_fridayservicestats"))
        self.gridLayout_30.addWidget(self.mpl_fridayservicestats, 0, 0, 1, 1)
        self.stackedWidget_fpm.addWidget(self.page_10)
        self.page_11 = QtGui.QWidget()
        self.page_11.setObjectName(_fromUtf8("page_11"))
        self.gridLayout_26 = QtGui.QGridLayout(self.page_11)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.mpl_fridayprayer_daily = MplWidget(self.page_11)
        self.mpl_fridayprayer_daily.setObjectName(_fromUtf8("mpl_fridayprayer_daily"))
        self.gridLayout_26.addWidget(self.mpl_fridayprayer_daily, 0, 0, 1, 1)
        self.stackedWidget_fpm.addWidget(self.page_11)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_22 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.mpl_fridayservicedeptstats = MplWidget(self.page_3)
        self.mpl_fridayservicedeptstats.setObjectName(_fromUtf8("mpl_fridayservicedeptstats"))
        self.gridLayout_22.addWidget(self.mpl_fridayservicedeptstats, 0, 0, 1, 1)
        self.stackedWidget_fpm.addWidget(self.page_3)
        self.horizontalLayout_5.addWidget(self.stackedWidget_fpm)
        self.gridLayout_16.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.pushButton_previous_graph_fpm = QtGui.QPushButton(self.tab_fridayprayer)
        self.pushButton_previous_graph_fpm.setObjectName(_fromUtf8("pushButton_previous_graph_fpm"))
        self.horizontalLayout_14.addWidget(self.pushButton_previous_graph_fpm)
        self.pushButton_next_graph_fpm = QtGui.QPushButton(self.tab_fridayprayer)
        self.pushButton_next_graph_fpm.setObjectName(_fromUtf8("pushButton_next_graph_fpm"))
        self.horizontalLayout_14.addWidget(self.pushButton_next_graph_fpm)
        self.gridLayout_16.addLayout(self.horizontalLayout_14, 0, 0, 1, 1)
        self.tabWidget_statistics.addTab(self.tab_fridayprayer, _fromUtf8(""))
        self.tab_dawnservice = QtGui.QWidget()
        self.tab_dawnservice.setObjectName(_fromUtf8("tab_dawnservice"))
        self.gridLayout_18 = QtGui.QGridLayout(self.tab_dawnservice)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.stackedWidget_ds = QtGui.QStackedWidget(self.tab_dawnservice)
        self.stackedWidget_ds.setObjectName(_fromUtf8("stackedWidget_ds"))
        self.page_12 = QtGui.QWidget()
        self.page_12.setObjectName(_fromUtf8("page_12"))
        self.gridLayout_28 = QtGui.QGridLayout(self.page_12)
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.mpl_dawnservicestats = MplWidget(self.page_12)
        self.mpl_dawnservicestats.setObjectName(_fromUtf8("mpl_dawnservicestats"))
        self.gridLayout_28.addWidget(self.mpl_dawnservicestats, 0, 0, 1, 1)
        self.stackedWidget_ds.addWidget(self.page_12)
        self.page_13 = QtGui.QWidget()
        self.page_13.setObjectName(_fromUtf8("page_13"))
        self.gridLayout_27 = QtGui.QGridLayout(self.page_13)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.mpl_dawnservice_daily = MplWidget(self.page_13)
        self.mpl_dawnservice_daily.setObjectName(_fromUtf8("mpl_dawnservice_daily"))
        self.gridLayout_27.addWidget(self.mpl_dawnservice_daily, 0, 0, 1, 1)
        self.stackedWidget_ds.addWidget(self.page_13)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.gridLayout_23 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.mpl_dawnservicedeptstats = MplWidget(self.page_4)
        self.mpl_dawnservicedeptstats.setObjectName(_fromUtf8("mpl_dawnservicedeptstats"))
        self.gridLayout_23.addWidget(self.mpl_dawnservicedeptstats, 0, 0, 1, 1)
        self.stackedWidget_ds.addWidget(self.page_4)
        self.horizontalLayout_6.addWidget(self.stackedWidget_ds)
        self.gridLayout_18.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.pushButton_previous_graph_ds = QtGui.QPushButton(self.tab_dawnservice)
        self.pushButton_previous_graph_ds.setObjectName(_fromUtf8("pushButton_previous_graph_ds"))
        self.horizontalLayout_15.addWidget(self.pushButton_previous_graph_ds)
        self.pushButton_next_graph_ds = QtGui.QPushButton(self.tab_dawnservice)
        self.pushButton_next_graph_ds.setObjectName(_fromUtf8("pushButton_next_graph_ds"))
        self.horizontalLayout_15.addWidget(self.pushButton_next_graph_ds)
        self.gridLayout_18.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        self.tabWidget_statistics.addTab(self.tab_dawnservice, _fromUtf8(""))
        self.gridLayout_8.addWidget(self.tabWidget_statistics, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.label_2 = QtGui.QLabel(self.tab_statistics)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_monthselector = QtGui.QComboBox(self.tab_statistics)
        self.comboBox_monthselector.setObjectName(_fromUtf8("comboBox_monthselector"))
        self.horizontalLayout_2.addWidget(self.comboBox_monthselector)
        self.label_3 = QtGui.QLabel(self.tab_statistics)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBox_yearselector = QtGui.QComboBox(self.tab_statistics)
        self.comboBox_yearselector.setObjectName(_fromUtf8("comboBox_yearselector"))
        self.horizontalLayout_2.addWidget(self.comboBox_yearselector)
        self.pushButton_plot = QtGui.QPushButton(self.tab_statistics)
        self.pushButton_plot.setObjectName(_fromUtf8("pushButton_plot"))
        self.horizontalLayout_2.addWidget(self.pushButton_plot)
        self.gridLayout_9.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.tab_widget.addTab(self.tab_statistics, _fromUtf8(""))
        self.tab_admin = QtGui.QWidget()
        self.tab_admin.setObjectName(_fromUtf8("tab_admin"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_admin)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tabWidget_adminmarking = QtGui.QTabWidget(self.tab_admin)
        self.tabWidget_adminmarking.setMovable(False)
        self.tabWidget_adminmarking.setObjectName(_fromUtf8("tabWidget_adminmarking"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(17, 25, 521, 369))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.formLayout_5 = QtGui.QFormLayout(self.layoutWidget1)
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_admintab_dept = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_admintab_dept.setFont(font)
        self.label_admintab_dept.setObjectName(_fromUtf8("label_admintab_dept"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_admintab_dept)
        self.comboBox_admintab_dept = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_admintab_dept.setObjectName(_fromUtf8("comboBox_admintab_dept"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_admintab_dept)
        self.label_admintab_name = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_admintab_name.setFont(font)
        self.label_admintab_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_admintab_name.setObjectName(_fromUtf8("label_admintab_name"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_admintab_name)
        self.comboBox_admintab_name = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_admintab_name.setObjectName(_fromUtf8("comboBox_admintab_name"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox_admintab_name)
        self.label_admintab_event = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_admintab_event.setFont(font)
        self.label_admintab_event.setObjectName(_fromUtf8("label_admintab_event"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_admintab_event)
        self.comboBox_admintab_event = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_admintab_event.setObjectName(_fromUtf8("comboBox_admintab_event"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBox_admintab_event)
        self.label = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.label)
        self.calendarWidget = QtGui.QCalendarWidget(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.calendarWidget)
        self.label_admintab_status = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_admintab_status.setFont(font)
        self.label_admintab_status.setObjectName(_fromUtf8("label_admintab_status"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_admintab_status)
        self.comboBox_admintab_status = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_admintab_status.setObjectName(_fromUtf8("comboBox_admintab_status"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.comboBox_admintab_status)
        self.label_static_admintab_remarks = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_static_admintab_remarks.setFont(font)
        self.label_static_admintab_remarks.setObjectName(_fromUtf8("label_static_admintab_remarks"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_static_admintab_remarks)
        self.label_admintab_dynamic_remarks = QtGui.QLabel(self.layoutWidget1)
        self.label_admintab_dynamic_remarks.setText(_fromUtf8(""))
        self.label_admintab_dynamic_remarks.setWordWrap(True)
        self.label_admintab_dynamic_remarks.setObjectName(_fromUtf8("label_admintab_dynamic_remarks"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.FieldRole, self.label_admintab_dynamic_remarks)
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(17, 410, 315, 29))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButton_submit = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_submit.setObjectName(_fromUtf8("pushButton_submit"))
        self.horizontalLayout_7.addWidget(self.pushButton_submit)
        self.pushButton_delete = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_delete.setObjectName(_fromUtf8("pushButton_delete"))
        self.horizontalLayout_7.addWidget(self.pushButton_delete)
        self.pushButton_reload_attlist = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_reload_attlist.setObjectName(_fromUtf8("pushButton_reload_attlist"))
        self.horizontalLayout_7.addWidget(self.pushButton_reload_attlist)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.tabWidget_adminmarking.addTab(self.tab_5, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_17 = QtGui.QGridLayout(self.tab)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.mpl_memberscount = MplWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_memberscount.sizePolicy().hasHeightForWidth())
        self.mpl_memberscount.setSizePolicy(sizePolicy)
        self.mpl_memberscount.setObjectName(_fromUtf8("mpl_memberscount"))
        self.gridLayout_17.addWidget(self.mpl_memberscount, 0, 0, 1, 1)
        self.tabWidget_adminmarking.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.comboBox_viewtabledept = QtGui.QComboBox(self.tab_3)
        self.comboBox_viewtabledept.setObjectName(_fromUtf8("comboBox_viewtabledept"))
        self.gridLayout_4.addWidget(self.comboBox_viewtabledept, 1, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 1, 4, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.tab_3)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidget, 0, 0, 1, 5)
        self.pushButton_commitchange = QtGui.QPushButton(self.tab_3)
        self.pushButton_commitchange.setObjectName(_fromUtf8("pushButton_commitchange"))
        self.gridLayout_4.addWidget(self.pushButton_commitchange, 1, 3, 1, 1)
        self.pushButton_loadmemberdetails = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_loadmemberdetails.sizePolicy().hasHeightForWidth())
        self.pushButton_loadmemberdetails.setSizePolicy(sizePolicy)
        self.pushButton_loadmemberdetails.setObjectName(_fromUtf8("pushButton_loadmemberdetails"))
        self.gridLayout_4.addWidget(self.pushButton_loadmemberdetails, 1, 2, 1, 1)
        self.tabWidget_adminmarking.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 0, 891, 431))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox_6)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 321, 331))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setMargin(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.nameLabel = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName(_fromUtf8("nameLabel"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.nameLineEdit.setObjectName(_fromUtf8("nameLineEdit"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.nameLineEdit)
        self.englishNameLabel = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.englishNameLabel.setFont(font)
        self.englishNameLabel.setObjectName(_fromUtf8("englishNameLabel"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.englishNameLabel)
        self.englishNameLineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.englishNameLineEdit.setObjectName(_fromUtf8("englishNameLineEdit"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.englishNameLineEdit)
        self.genderLabel = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.genderLabel.setFont(font)
        self.genderLabel.setObjectName(_fromUtf8("genderLabel"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.genderLabel)
        self.comboBox_addmembergender = QtGui.QComboBox(self.formLayoutWidget_2)
        self.comboBox_addmembergender.setObjectName(_fromUtf8("comboBox_addmembergender"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBox_addmembergender)
        self.deptLabel = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.deptLabel.setFont(font)
        self.deptLabel.setObjectName(_fromUtf8("deptLabel"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.deptLabel)
        self.comboBox_addmemberdept = QtGui.QComboBox(self.formLayoutWidget_2)
        self.comboBox_addmemberdept.setObjectName(_fromUtf8("comboBox_addmemberdept"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBox_addmemberdept)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_7)
        self.contactNum_lineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.contactNum_lineEdit.setObjectName(_fromUtf8("contactNum_lineEdit"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.contactNum_lineEdit)
        self.formLayoutWidget = QtGui.QWidget(self.groupBox_6)
        self.formLayoutWidget.setGeometry(QtCore.QRect(330, 18, 521, 361))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout_6 = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_6.setMargin(0)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.calendarWidget_newmember_dob = QtGui.QCalendarWidget(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget_newmember_dob.sizePolicy().hasHeightForWidth())
        self.calendarWidget_newmember_dob.setSizePolicy(sizePolicy)
        self.calendarWidget_newmember_dob.setGridVisible(True)
        self.calendarWidget_newmember_dob.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget_newmember_dob.setNavigationBarVisible(True)
        self.calendarWidget_newmember_dob.setObjectName(_fromUtf8("calendarWidget_newmember_dob"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.calendarWidget_newmember_dob)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.calendarWidget_newmember_passing = QtGui.QCalendarWidget(self.formLayoutWidget)
        self.calendarWidget_newmember_passing.setGridVisible(True)
        self.calendarWidget_newmember_passing.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget_newmember_passing.setObjectName(_fromUtf8("calendarWidget_newmember_passing"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.calendarWidget_newmember_passing)
        self.pushButton_addmember = QtGui.QPushButton(self.tab_4)
        self.pushButton_addmember.setGeometry(QtCore.QRect(10, 430, 98, 27))
        self.pushButton_addmember.setObjectName(_fromUtf8("pushButton_addmember"))
        self.tabWidget_adminmarking.addTab(self.tab_4, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 981, 431))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.formLayoutWidget_3 = QtGui.QWidget(self.groupBox_7)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 331, 231))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_7 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_7.setMargin(0)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.nameLabel_2 = QtGui.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel_2.setFont(font)
        self.nameLabel_2.setObjectName(_fromUtf8("nameLabel_2"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.nameLabel_2)
        self.englishNameLabel_2 = QtGui.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.englishNameLabel_2.setFont(font)
        self.englishNameLabel_2.setObjectName(_fromUtf8("englishNameLabel_2"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.englishNameLabel_2)
        self.englishNameLineEdit_2 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.englishNameLineEdit_2.setObjectName(_fromUtf8("englishNameLineEdit_2"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.englishNameLineEdit_2)
        self.genderLabel_2 = QtGui.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.genderLabel_2.setFont(font)
        self.genderLabel_2.setObjectName(_fromUtf8("genderLabel_2"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.genderLabel_2)
        self.deptLabel_2 = QtGui.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.deptLabel_2.setFont(font)
        self.deptLabel_2.setObjectName(_fromUtf8("deptLabel_2"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.LabelRole, self.deptLabel_2)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_2 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_7.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_10)
        self.englishNameLineEdit_3 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.englishNameLineEdit_3.setObjectName(_fromUtf8("englishNameLineEdit_3"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.FieldRole, self.englishNameLineEdit_3)
        self.lineEdit_3 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.formLayout_7.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_4 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_4)
        self.comboBox_profilename = QtGui.QComboBox(self.formLayoutWidget_3)
        self.comboBox_profilename.setObjectName(_fromUtf8("comboBox_profilename"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_profilename)
        self.comboBox_profiledept = QtGui.QComboBox(self.formLayoutWidget_3)
        self.comboBox_profiledept.setObjectName(_fromUtf8("comboBox_profiledept"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBox_profiledept)
        self.label_11 = QtGui.QLabel(self.groupBox_7)
        self.label_11.setGeometry(QtCore.QRect(340, 20, 221, 231))
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setPixmap(QtGui.QPixmap(_fromUtf8("../unknown_profile.png")))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_personalpic = QtGui.QLabel(self.groupBox_7)
        self.label_personalpic.setGeometry(QtCore.QRect(350, 20, 231, 191))
        self.label_personalpic.setText(_fromUtf8(""))
        self.label_personalpic.setPixmap(QtGui.QPixmap(_fromUtf8("../pyQt/unknown_profile.png")))
        self.label_personalpic.setObjectName(_fromUtf8("label_personalpic"))
        self.tabWidget_adminmarking.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_7.addWidget(self.tabWidget_adminmarking, 0, 0, 1, 1)
        self.tab_widget.addTab(self.tab_admin, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.tab_widget, 1, 0, 1, 1)
        LWCAttendanceTaker.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(LWCAttendanceTaker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFlie = QtGui.QMenu(self.menubar)
        self.menuFlie.setObjectName(_fromUtf8("menuFlie"))
        LWCAttendanceTaker.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(LWCAttendanceTaker)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        LWCAttendanceTaker.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(LWCAttendanceTaker)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionConnect = QtGui.QAction(LWCAttendanceTaker)
        self.actionConnect.setObjectName(_fromUtf8("actionConnect"))
        self.menuFlie.addAction(self.actionConnect)
        self.menuFlie.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFlie.menuAction())

        self.retranslateUi(LWCAttendanceTaker)
        self.tab_widget.setCurrentIndex(1)
        self.tabWidget_statistics.setCurrentIndex(0)
        self.stackedWidget_ss.setCurrentIndex(0)
        self.stackedWidget_ws.setCurrentIndex(0)
        self.stackedWidget_fpm.setCurrentIndex(0)
        self.stackedWidget_ds.setCurrentIndex(0)
        self.tabWidget_adminmarking.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LWCAttendanceTaker)

    def retranslateUi(self, LWCAttendanceTaker):
        LWCAttendanceTaker.setWindowTitle(_translate("LWCAttendanceTaker", "LWC Attendance Taker", None))
        self.pushButton_quit.setText(_translate("LWCAttendanceTaker", "Quit", None))
        self.groupBox.setTitle(_translate("LWCAttendanceTaker", "Serial Port Selection", None))
        self.pushButton_refresh.setText(_translate("LWCAttendanceTaker", "Refresh", None))
        self.pushButton_connect.setText(_translate("LWCAttendanceTaker", "Connect", None))
        self.pushButton_disconnect.setText(_translate("LWCAttendanceTaker", "Disconnect", None))
        self.groupBox_5.setTitle(_translate("LWCAttendanceTaker", "Database Parameter", None))
        self.pushButton_dbconnect.setText(_translate("LWCAttendanceTaker", "Connect to database", None))
        self.databaseHostLabel.setText(_translate("LWCAttendanceTaker", "Database Server Host IP", None))
        self.pushButton_connecttohome.setText(_translate("LWCAttendanceTaker", "Connect to 127.0.0.1", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_6), _translate("LWCAttendanceTaker", "Setup", None))
        self.label_4.setText(_translate("LWCAttendanceTaker", "Welcome! Swipe ID for attendance!", None))
        self.groupBox_4.setTitle(_translate("LWCAttendanceTaker", "What\'s up?", None))
        self.label_static_time.setText(_translate("LWCAttendanceTaker", "Time:", None))
        self.label_static_date.setText(_translate("LWCAttendanceTaker", "Date:", None))
        self.label_static_event.setText(_translate("LWCAttendanceTaker", "Event:", None))
        self.groupBox_2.setTitle(_translate("LWCAttendanceTaker", "Identification", None))
        self.label_static_name.setText(_translate("LWCAttendanceTaker", "Name:", None))
        self.label_static_rfid.setText(_translate("LWCAttendanceTaker", "RFID:", None))
        self.label_static_dept.setText(_translate("LWCAttendanceTaker", "Dept:", None))
        self.label_static_status.setText(_translate("LWCAttendanceTaker", "Status:", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_attendance), _translate("LWCAttendanceTaker", "Attendance", None))
        self.pushButton_previous_graph_ss.setText(_translate("LWCAttendanceTaker", "Previous", None))
        self.pushButton_next_graph_ss.setText(_translate("LWCAttendanceTaker", "Next", None))
        self.tabWidget_statistics.setTabText(self.tabWidget_statistics.indexOf(self.tab_sundayservice), _translate("LWCAttendanceTaker", "Sunday Service", None))
        self.pushButton_previous_graph_ws.setText(_translate("LWCAttendanceTaker", "Previous", None))
        self.pushButton_next_graph_ws.setText(_translate("LWCAttendanceTaker", "Next", None))
        self.tabWidget_statistics.setTabText(self.tabWidget_statistics.indexOf(self.tab_wednesdayservice), _translate("LWCAttendanceTaker", "Wednesday Service", None))
        self.pushButton_previous_graph_fpm.setText(_translate("LWCAttendanceTaker", "Previous", None))
        self.pushButton_next_graph_fpm.setText(_translate("LWCAttendanceTaker", "Next", None))
        self.tabWidget_statistics.setTabText(self.tabWidget_statistics.indexOf(self.tab_fridayprayer), _translate("LWCAttendanceTaker", "Friday Prayer", None))
        self.pushButton_previous_graph_ds.setText(_translate("LWCAttendanceTaker", "Previous", None))
        self.pushButton_next_graph_ds.setText(_translate("LWCAttendanceTaker", "Next", None))
        self.tabWidget_statistics.setTabText(self.tabWidget_statistics.indexOf(self.tab_dawnservice), _translate("LWCAttendanceTaker", "Dawn Service", None))
        self.label_2.setText(_translate("LWCAttendanceTaker", "Month", None))
        self.label_3.setText(_translate("LWCAttendanceTaker", "Year", None))
        self.pushButton_plot.setText(_translate("LWCAttendanceTaker", "Plot Graph", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_statistics), _translate("LWCAttendanceTaker", "Service Statistics", None))
        self.groupBox_3.setTitle(_translate("LWCAttendanceTaker", "Attendance Marking", None))
        self.label_admintab_dept.setText(_translate("LWCAttendanceTaker", "Dept", None))
        self.label_admintab_name.setText(_translate("LWCAttendanceTaker", "Name", None))
        self.label_admintab_event.setText(_translate("LWCAttendanceTaker", "Event Type", None))
        self.label.setText(_translate("LWCAttendanceTaker", "Event Date", None))
        self.label_admintab_status.setText(_translate("LWCAttendanceTaker", "Status", None))
        self.label_static_admintab_remarks.setText(_translate("LWCAttendanceTaker", "Remarks", None))
        self.pushButton_submit.setText(_translate("LWCAttendanceTaker", "Submit", None))
        self.pushButton_delete.setText(_translate("LWCAttendanceTaker", "Delete", None))
        self.pushButton_reload_attlist.setText(_translate("LWCAttendanceTaker", "Reload", None))
        self.tabWidget_adminmarking.setTabText(self.tabWidget_adminmarking.indexOf(self.tab_5), _translate("LWCAttendanceTaker", "Admin Marking", None))
        self.tabWidget_adminmarking.setTabText(self.tabWidget_adminmarking.indexOf(self.tab), _translate("LWCAttendanceTaker", "Members Count", None))
        self.pushButton_commitchange.setText(_translate("LWCAttendanceTaker", "Commit Changes", None))
        self.pushButton_loadmemberdetails.setText(_translate("LWCAttendanceTaker", "Load", None))
        self.tabWidget_adminmarking.setTabText(self.tabWidget_adminmarking.indexOf(self.tab_3), _translate("LWCAttendanceTaker", "Edit Members\' Details", None))
        self.groupBox_6.setTitle(_translate("LWCAttendanceTaker", "Add New Member", None))
        self.nameLabel.setText(_translate("LWCAttendanceTaker", "Name", None))
        self.englishNameLabel.setText(_translate("LWCAttendanceTaker", "English Name", None))
        self.genderLabel.setText(_translate("LWCAttendanceTaker", "Gender", None))
        self.deptLabel.setText(_translate("LWCAttendanceTaker", "Dept", None))
        self.label_7.setText(_translate("LWCAttendanceTaker", "Contact Num", None))
        self.label_5.setText(_translate("LWCAttendanceTaker", "Date of Birth", None))
        self.label_6.setText(_translate("LWCAttendanceTaker", "Passing Date", None))
        self.pushButton_addmember.setText(_translate("LWCAttendanceTaker", "Add!", None))
        self.tabWidget_adminmarking.setTabText(self.tabWidget_adminmarking.indexOf(self.tab_4), _translate("LWCAttendanceTaker", "Add New Members", None))
        self.groupBox_7.setTitle(_translate("LWCAttendanceTaker", "Profile", None))
        self.nameLabel_2.setText(_translate("LWCAttendanceTaker", "Name", None))
        self.englishNameLabel_2.setText(_translate("LWCAttendanceTaker", "English Name", None))
        self.genderLabel_2.setText(_translate("LWCAttendanceTaker", "Gender", None))
        self.deptLabel_2.setText(_translate("LWCAttendanceTaker", "Dept", None))
        self.label_8.setText(_translate("LWCAttendanceTaker", "Contact Num", None))
        self.label_9.setText(_translate("LWCAttendanceTaker", "Date of Birth", None))
        self.label_10.setText(_translate("LWCAttendanceTaker", "Passing Date", None))
        self.tabWidget_adminmarking.setTabText(self.tabWidget_adminmarking.indexOf(self.tab_2), _translate("LWCAttendanceTaker", "Personal Profile", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_admin), _translate("LWCAttendanceTaker", "Administration", None))
        self.menuFlie.setTitle(_translate("LWCAttendanceTaker", "File", None))
        self.actionQuit.setText(_translate("LWCAttendanceTaker", "Quit", None))
        self.actionConnect.setText(_translate("LWCAttendanceTaker", "Connect", None))

from mplwidget import MplWidget
